#!/usr/bin/env python3
"""Print the CA-004 braking-authority study results as markdown (FI-2026-001 evidence)."""
import subprocess

from openpilot.cereal import log
from openpilot.selfdrive.test.stopped_vehicle import scenarios as S
from openpilot.selfdrive.test.stopped_vehicle.emergency_brake import EmergencyBrakeConfig
from openpilot.selfdrive.test.stopped_vehicle.harness import REFERENCE_CAR, run

OPTIONS = (
  ("(a) -3.5 m/s² (current)", None),
  ("(b) emergency -6 m/s²", EmergencyBrakeConfig(decel=6.)),
  ("(b) emergency -8 m/s²", EmergencyBrakeConfig(decel=8.)),
)
REVEAL_GAPS = (30., 50., 80., 120., 160.)
LEAD_DECELS = (3., 4., 6., 8.)
CONFIRMATION_RANGES = (60., 90., 120., 150.)


def impact(scenario, emergency):
  r = run(scenario, emergency)
  return f"**{r.impact_speed * 3.6:.0f}**" if r.collided else "0"


def bisect(collides, lo, hi, tol):
  """Smallest value in [lo, hi] for which collides() is False, assuming it is monotonic."""
  while hi - lo > tol:
    mid = (lo + hi) / 2
    if collides(mid):
      lo = mid
    else:
      hi = mid
  return hi


def min_vision_range(v_ego, emergency):
  return bisect(lambda d: run(S.Scenario("bisect", v_ego, initial_gap=d + 2 * v_ego, vision_range=d), emergency).collided,
                0., 400., 0.5)


def max_speed_kph(confirmation_range, emergency):
  def collides(kph):
    v = kph / 3.6
    return run(S.Scenario("bisect", v, initial_gap=confirmation_range + 2 * v, vision_range=confirmation_range), emergency).collided
  lo, hi = 10., 200.  # no collision at lo, collision at hi
  while hi - lo > 1.:
    mid = (lo + hi) / 2
    if collides(mid):
      hi = mid
    else:
      lo = mid
  return lo


def rear_end(v0, ego_decel, headway, reaction, follower_decel, jerk=20., dt=0.01):
  """Impact speed (m/s) of a following car that brakes after a reaction time, or 0 if it stops in time."""
  x_e, v_e, a_e = headway * v0, v0, 0.
  x_f, v_f, a_f = 0., v0, 0.
  t = 0.
  while v_f > 0.:
    a_e = max(-ego_decel, a_e - jerk * dt) if v_e > 0. else 0.
    if t >= reaction:
      a_f = max(-follower_decel, a_f - jerk * dt)
    v_e, v_f = max(0., v_e + a_e * dt), max(0., v_f + a_f * dt)
    x_e, x_f = x_e + v_e * dt, x_f + v_f * dt
    if x_f >= x_e:
      return v_f - v_e
    t += dt
  return 0.


def table(header, rows):
  lines = ["| " + " | ".join(header) + " |", "|" + "---|" * len(header)]
  lines += ["| " + " | ".join(row) + " |" for row in rows]
  return "\n".join(lines)


def main():
  commit = subprocess.run(["git", "rev-parse", "--short", "HEAD"], capture_output=True, text=True).stdout.strip()
  script = "openpilot/selfdrive/test/stopped_vehicle/braking_authority_study.py"
  print(f"Generated by `{script}` at commit `{commit}`, reference car `{REFERENCE_CAR}`. Impact speeds in km/h; **bold** = collision.\n")
  names = [name for name, _ in OPTIONS]

  print("### S1. Required confirmation range, stopped vehicle (m)\n")
  print(table(["Ego speed (km/h)", *names], [[str(kph), *(f"{min_vision_range(kph / 3.6, e):.0f}" for _, e in OPTIONS)]
                                            for kph in S.SPEEDS_KPH]))

  print("\n### S2. Cut-out reveal of a stopped vehicle: impact speed\n")
  rows = [[str(kph), f"{gap:.0f}", *(impact(S.cut_out(kph, gap), e) for _, e in OPTIONS)]
          for kph in S.SPEEDS_KPH for gap in REVEAL_GAPS]
  print(table(["Ego speed (km/h)", "Reveal gap (m)", *names], rows))

  print("\n### S3. Lead vehicle brakes to a stop: impact speed\n")
  print("Steady following at the standard personality's distance, plus the current authority at the relaxed distance.\n")
  relaxed = log.LongitudinalPersonality.relaxed
  rows = [[str(kph), f"{d:.0f}", *(impact(S.lead_braking(kph, d), e) for _, e in OPTIONS), impact(S.lead_braking(kph, d, relaxed), None)]
          for kph in (60, 100, 120) for d in LEAD_DECELS]
  print(table(["Ego speed (km/h)", "Lead decel (m/s²)", *names, "(a) at relaxed distance"], rows))

  print("\n### S4. Option (c): highest speed without collision for a given confirmation range (km/h)\n")
  print(table(["Confirmation range (m)", *names], [[f"{d:.0f}", *(f"{max_speed_kph(d, e):.0f}" for _, e in OPTIONS)]
                                                    for d in CONFIRMATION_RANGES]))

  print("\n### S5. Rear-end exposure (HZ-007): impact speed of a following car, ego braking to a stop from 100 km/h\n")
  print("Following driver reacts after 1.5 s, then brakes at 6 m/s² (8 m/s² in brackets). Jerk 20 m/s³ for both.\n")
  rows = []
  for headway in (0.8, 1.0, 1.5, 2.0):
    cells = []
    for ego_decel in (3.5, 6., 8.):
      v6, v8 = (rear_end(100 / 3.6, ego_decel, headway, 1.5, fd) * 3.6 for fd in (6., 8.))
      cells.append(f"{v6:.0f} ({v8:.0f})")
    rows.append([f"{headway:.1f}", *cells])
  print(table(["Follower headway (s)", "Ego -3.5 m/s²", "Ego -6 m/s²", "Ego -8 m/s²"], rows))


if __name__ == "__main__":
  main()
