#!/usr/bin/env python3
"""Print the CA-002 baseline results as markdown (FI-2026-001 evidence)."""
import argparse
import subprocess

from openpilot.selfdrive.test.stopped_vehicle import scenarios as S
from openpilot.selfdrive.test.stopped_vehicle.harness import REFERENCE_CAR, run


def min_vision_range(v_ego: float, v_target: float = 0., radar_range: float = 175.) -> float:
  """Smallest vision confirmation range that avoids a collision, by bisection (0.1 m)."""
  lo, hi = 0., 400.
  while hi - lo > 0.1:
    mid = (lo + hi) / 2
    scenario = S.Scenario("bisect", v_ego, v_target, initial_gap=mid + 2 * v_ego, vision_range=mid, radar_range=radar_range)
    if run(scenario).collided:
      lo = mid
    else:
      hi = mid
  return hi


def fmt(value, digits=1):
  return "—" if value is None else f"{value:.{digits}f}"


def results_table(scenarios):
  rows = ["| Scenario | Collision | Impact speed (km/h) | First detection gap (m) | FCW TTC (s) | Min gap (m) | Peak decel (m/s²) |",
          "|---|---|---|---|---|---|---|"]
  for scenario in scenarios:
    r = run(scenario)
    cells = [scenario.name, "**yes**" if r.collided else "no", fmt(r.impact_speed * 3.6) if r.collided else "—",
             fmt(r.first_detection_gap), fmt(r.fcw_ttc, 2), fmt(max(r.min_gap, 0.)), f"{r.peak_decel:.2f}"]
    rows.append("| " + " | ".join(cells) + " |")
  return "\n".join(rows)


def main():
  parser = argparse.ArgumentParser(description=__doc__)
  parser.parse_args()

  commit = subprocess.run(["git", "rev-parse", "--short", "HEAD"], capture_output=True, text=True).stdout.strip()
  print(f"Generated by `openpilot/selfdrive/test/stopped_vehicle/report.py` at commit `{commit}`, reference car `{REFERENCE_CAR}`.\n")

  print("### Required detection range\n")
  estimate = f"RCA §3.1 estimate ({S.LATENCY} s latency, {S.BRAKE_LIMIT} m/s²)"
  print(f"Smallest vision confirmation range that avoids a collision, compared with the {estimate}.\n")
  print("| Ego speed (km/h) | Target | RCA estimate (m) | Simulated, vision + radar (m) | Simulated, vision only (m) |")
  print("|---|---|---|---|---|")
  for kph in S.SPEEDS_KPH:
    v = kph / 3.6
    for label, v_target in (("stopped", 0.), ("slow (20%)", 0.2 * v)):
      cells = [str(kph), label, f"{S.required_stopping_distance(v, v_target):.1f}", f"{min_vision_range(v, v_target):.1f}",
               f"{min_vision_range(v, v_target, radar_range=0.):.1f}"]
      print("| " + " | ".join(cells) + " |")

  for title, scenarios in (("AC-1: visible from range (stopped)", S.VISIBLE_FROM_RANGE),
                           ("AC-1: visible from range (slow vehicle)", S.SLOW_VEHICLE),
                           ("AC-2: cut-out reveal", S.CUT_OUT),
                           ("Known gap: radar-only stationary target", S.RADAR_ONLY)):
    print(f"\n### {title}\n")
    print(results_table(scenarios))


if __name__ == "__main__":
  main()
