#!/usr/bin/env python3
"""Export assurance/08-analyses/fmea/analyses/fsc.yaml to an xlsx workbook for review.

Usage: tools/safety/export_fsc_xlsx.py [OUTPUT.xlsx] [--root REPO_ROOT]

Uses the tab names and column headers of fsc-builder (jherrodthomas/automotive-skills-suite)
so fsc-checklist-reviewer can read it. A faithful rendering of fsc.yaml: nothing is added.
There is no fault-tree tab because the FSC is not FTA-derived; unknown FTTIs are left blank.

Requires PyYAML, jsonschema and openpyxl.
"""
import argparse
import sys
from pathlib import Path

from openpyxl import Workbook

sys.path.insert(0, str(Path(__file__).resolve().parent))
import fmea_lint
from export_hara_xlsx import _rows, _sheet

DEFAULT_OUT = Path("assurance/08-analyses/fmea/exports/fsc.xlsx")


def build(root: Path) -> Workbook:
  safety = root / fmea_lint.SAFETY_DIR
  fsc = fmea_lint.load_yaml((safety / "analyses/fsc.yaml").read_text())
  hara = fmea_lint.load_yaml((safety / "analyses/hara.yaml").read_text())
  hdr = fsc["analysis"]
  sgs = {sg["id"]: sg for sg in hara["safety_goals"]}
  hazards = {h["id"]: h for h in hara["hazards"]}
  elements = {e["id"]: e for e in fsc["elements"]}
  fsrs = {f["id"]: f for f in fsc["fsrs"]}
  timing = {t["safety_goal"]: t for t in fsc["timing"]}
  parent_of = {k: f for f in fsc["fsrs"] for k in f.get("decomposition", {}).get("into", [])}
  # fsc-checklist-reviewer only accepts node IDs starting with "N"; show EL-xx as Nxx and keep the EL id beside it.
  node = {el: "N" + el.split("-")[1] for el in elements}

  def nodes(ids):
    return ", ".join(node[i] for i in ids)

  wb = Workbook()
  wb.remove(wb.active)

  ws, r = _sheet(wb, "00_Title_Page", hdr["title"])
  _rows(ws, r, [
    ["Document Title", hdr["title"]],
    ["Project", "LionDriver"],
    ["Document ID", hdr.get("doc_id", "")],
    ["Revision", hdr["revision"]],
    ["Status", hdr["status"]],
    ["Date", hdr.get("updated", "")],
    ["Author", "; ".join(f"{t['name']} ({t['role']})" for t in hdr.get("team", []))],
    ["Approver", hdr.get("approver", "")],
    ["Linked HARA", f"LD-HARA-001 rev {hdr['hara_revision']}"],
    ["Node IDs", "Architecture elements EL-xx are shown as node IDs Nxx; the Element column keeps the EL id"],
    ["Scope", hdr["scope"]],
    ["Source", "assurance/08-analyses/fmea/analyses/fsc.yaml (generated by tools/safety/export_fsc_xlsx.py; do not edit)"],
  ])
  ws.column_dimensions["A"].width = 18
  ws.column_dimensions["B"].width = 110

  ws, r = _sheet(wb, "01_Document_Control", "Document Control", ["Revision", "Date", "Author", "Change"])
  _rows(ws, r, [[h["revision"], h["date"], h["author"], h["change"]] for h in hdr.get("history", [])])

  ws, r = _sheet(wb, "02_SGs_From_HARA", "Safety Goals (from HARA)", ["SG_ID", "Function", "Hazard", "ASIL", "Safety Goal", "Safe State"])
  _rows(ws, r, [[sg["id"], ", ".join(dict.fromkeys(f for h in sg["hazards"] for f in hazards[h]["functions"])),
                 "; ".join(f"{h} {hazards[h]['description']}" for h in sg["hazards"]), sg["asil"], sg["statement"], sg["safe_state"]]
                for sg in hara["safety_goals"]])

  ws, r = _sheet(wb, "03_System_Block_Diagram", "Preliminary Architecture",
                 ["Node ID", "Element", "Name", "Type", "ASIL-relevant", "ASIL capability", "Capability status", "Inputs", "Outputs",
                  "Redundancy group", "Shared resources", "Description"])
  _rows(ws, r, [[node[e["id"]], e["id"], e["name"], e["type"], "No" if e["type"] == "external" else "Yes", e["asil_capability"],
                 e["capability_status"], nodes(e.get("inputs", [])), nodes(e.get("outputs", [])), "",
                 ", ".join(e.get("shared_resources", [])), e["description"]] for e in fsc["elements"]])

  ws, r = _sheet(wb, "05_FSR_Catalog", "Functional Safety Requirements",
                 ["FSR_ID", "SG_ID", "ASIL", "Branch", "Linked Node", "Functional Safety Requirement", "FTTI (ms)", "FTTI status",
                  "Safe state", "Decomposed from", "Implementation", "Implementation ref"])
  _rows(ws, r, [[f["id"], f["safety_goal"], f["asil"], f["kind"], nodes(f["allocated_to"]), f["statement"],
                 timing[f["safety_goal"]]["ftti_ms"], timing[f["safety_goal"]]["ftti_status"], f["safe_state"],
                 parent_of[f["id"]]["id"] if f["id"] in parent_of else "", f["implementation"]["status"],
                 f["implementation"].get("ref", "") or f["implementation"].get("note", "")] for f in fsc["fsrs"]])

  rows = []
  for f in fsc["fsrs"]:
    dec = f.get("decomposition")
    parent = parent_of.get(f["id"])
    if dec:
      sel = f"{f['asil']} -> " + " + ".join(fsrs[k]["asil"] for k in dec["into"])
      evidence = dec["independence"]
    elif parent:
      sel = f"{parent['asil']} -> " + " + ".join(fsrs[k]["asil"] for k in parent["decomposition"]["into"])
      evidence = parent["decomposition"]["independence"]
    else:
      sel, evidence = "None (full inheritance)", ""
    for el in f["allocated_to"]:
      rows.append([f["safety_goal"], f["id"], node[el], elements[el]["name"], f["kind"], sgs[f["safety_goal"]]["asil"], sel, f["asil"],
                   elements[el]["asil_capability"], evidence])
  ws, r = _sheet(wb, "06_ASIL_Allocation", "ASIL Allocation",
                 ["SG_ID", "FSR", "Node ID", "Node Name", "Branch", "Inherited ASIL", "Selected Decomposition", "Resulting ASIL",
                  "Element capability", "Independence Evidence"])
  _rows(ws, r, rows)

  ws, r = _sheet(wb, "07_Verification_Matrix", "Verification", ["FSR_ID", "ASIL", "Method", "Existing test", "Planned"])
  _rows(ws, r, [[f["id"], f["asil"], v["method"], v.get("test", ""), v.get("planned", "")] for f in fsc["fsrs"] for v in f["verification"]])

  ws, r = _sheet(wb, "08_TSC_Handoff", "TSC Hand-off", ["FSR_ID", "ASIL", "Allocated to", "TSR (to be derived in TSC)", "Open items"])
  _rows(ws, r, [[f["id"], f["asil"], nodes(f["allocated_to"]), "", ", ".join(o["id"] for o in fsc["open_items"] if f["id"] in o["affects"])]
                for f in fsc["fsrs"]])

  ws, r = _sheet(wb, "09_Timing", "Fault Tolerant Time Intervals", ["SG_ID", "FTTI (ms)", "Status", "Basis"])
  _rows(ws, r, [[t["safety_goal"], t["ftti_ms"], t["ftti_status"], t["basis"]] for t in fsc["timing"]])

  ws, r = _sheet(wb, "10_Operating_Modes", "Operating Modes", ["ID", "Mode", "Actuation", "Description", "Ref"])
  _rows(ws, r, [[m["id"], m["name"], m["actuation"], m["description"], m.get("ref", "")] for m in fsc["operating_modes"]])

  ws, r = _sheet(wb, "11_Warning_Degradation", "Warning and Degradation Concept",
                 ["ID", "Trigger", "Reaction", "Driver warning", "Time to safe state", "Ref"])
  _rows(ws, r, [[w["id"], w["trigger"], w["reaction"], w["driver_warning"], w["time_to_safe_state"], w.get("ref", "")]
                for w in fsc["warning_degradation"]])

  ws, r = _sheet(wb, "12_External_Measures", "External Measures", ["ID", "Measure", "Credited", "Evidence", "Open item"])
  _rows(ws, r, [[x["id"], x["description"], "Yes" if x["credited"] else "No", x["evidence"], x.get("open_item", "")]
                for x in fsc["external_measures"]])

  ws, r = _sheet(wb, "13_Open_Items", "Open Items", ["ID", "Status", "Open item", "Affects", "Resolution"])
  _rows(ws, r, [[o["id"], o["status"], o["text"], ", ".join(o["affects"]), o.get("resolution", "")] for o in fsc["open_items"]])

  ws, r = _sheet(wb, "14_References", "References", ["Reference"])
  _rows(ws, r, [[ref] for ref in hdr.get("references", [])])
  return wb


def main(argv=None) -> int:
  ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
  ap.add_argument("output", nargs="?", type=Path)
  ap.add_argument("--root", type=Path, default=fmea_lint.ROOT)
  args = ap.parse_args(argv)
  root = args.root.resolve()

  res = fmea_lint.lint(root)
  if res.errors:
    print("\n".join(res.errors))
    print("refusing to export: fix lint errors first")
    return 1
  out = args.output or root / DEFAULT_OUT
  out.parent.mkdir(parents=True, exist_ok=True)
  build(root).save(out)
  print(f"wrote {out}")
  return 0


if __name__ == "__main__":
  sys.exit(main())
