#!/usr/bin/env python3
"""Export assurance/08-analyses/fmea/item-definition.md to an xlsx workbook for review.

Usage: tools/safety/export_item_xlsx.py [OUTPUT.xlsx] [--root REPO_ROOT]

Uses the tab names and column order of item-definition-builder (jherrodthomas/automotive-skills-suite)
so item-def-checklist-reviewer can read it. Content comes from the markdown tables of LD-ITEM-001,
item/variants.yaml and the generated vehicle catalog; nothing is added.

Requires PyYAML and openpyxl.
"""
import argparse
import re
import sys
from pathlib import Path

import yaml
from openpyxl import Workbook
from openpyxl.styles import Alignment, Font, PatternFill

sys.path.insert(0, str(Path(__file__).resolve().parent))
import gen_vehicle_catalog

ROOT = Path(__file__).resolve().parents[2]
ITEM = Path("assurance/08-analyses/fmea/item-definition.md")
DEFAULT_OUT = Path("assurance/08-analyses/fmea/exports/item-definition.xlsx")
HEADER_FILL = PatternFill("solid", fgColor="1F3864")


def section_text(md: str, heading: str) -> str:
  """Text from a heading line starting with `heading` up to the next heading of the same or higher level."""
  lines = md.splitlines()
  start = next(i for i, line in enumerate(lines) if line.startswith(heading))
  level = len(heading.split(" ", maxsplit=1)[0])
  out = []
  for line in lines[start + 1:]:
    m = re.match(r"^(#+) ", line)
    if m and len(m.group(1)) <= level:
      break
    out.append(line)
  return "\n".join(out)


def tables(text: str) -> list[list[dict]]:
  """All markdown tables in `text`, each as a list of row dicts keyed by header."""
  result, block = [], []
  for line in text.splitlines() + [""]:
    if line.startswith("|"):
      block.append(line)
      continue
    if len(block) >= 2:
      split = [[c.strip() for c in row.strip().strip("|").split("|")] for row in block]
      header, rows = split[0], split[2:]
      result.append([dict(zip(header, r, strict=False)) for r in rows])
    block = []
  return result


def kv_table(text: str) -> dict[str, str]:
  """Rows of a two-column '| **Key** | value |' table."""
  return {m.group(1): m.group(2).strip() for m in re.finditer(r"^\| \*\*(.+?)\*\* \| (.+?) \|$", text, re.M)}


def plain(s: str) -> str:
  return re.sub(r"\*\*|`", "", s)


def first_paragraphs(text: str) -> str:
  paras = [p.strip() for p in text.split("\n\n") if p.strip() and not p.strip().startswith(("|", "```", "#"))]
  return plain(" ".join(paras))


def sheet(wb, name, headers, rows, widths=None):
  ws = wb.create_sheet(name)
  for c, h in enumerate(headers, 1):
    cell = ws.cell(1, c, h)
    cell.font = Font(bold=True, color="FFFFFF")
    cell.fill = HEADER_FILL
  for r, row in enumerate(rows, 2):
    for c, v in enumerate(row, 1):
      ws.cell(r, c, plain(v) if isinstance(v, str) else v).alignment = Alignment(wrap_text=True, vertical="top")
  for c, w in enumerate(widths or [], 1):
    ws.column_dimensions[ws.cell(1, c).column_letter].width = w
  ws.freeze_panes = "A2"
  return ws


def kv_sheet(wb, name, pairs):
  ws = wb.create_sheet(name)
  for r, (k, v) in enumerate(pairs, 1):
    ws.cell(r, 1, k).font = Font(bold=True)
    ws.cell(r, 2, plain(v)).alignment = Alignment(wrap_text=True, vertical="top")
  ws.column_dimensions["A"].width = 24
  ws.column_dimensions["B"].width = 120
  return ws


def build(root: Path) -> Workbook:
  md = (root / ITEM).read_text()
  meta = kv_table(md.split("\n---\n")[0])
  variants = yaml.safe_load((root / gen_vehicle_catalog.VARIANTS).read_text())
  cars = gen_vehicle_catalog.parse_cars((root / gen_vehicle_catalog.CARS).read_text())
  status, _ = gen_vehicle_catalog.classify(cars, variants)

  wb = Workbook()
  wb.remove(wb.active)
  title = "LionDriver — Item Definition (platform, VF-001 Toyota Corolla E210, AC-001)"
  kv_sheet(wb, "00_Title_Page", [
    ("Item Definition Title", title), ("Project", "LionDriver"), ("Document ID", meta["Doc ID"]), ("Revision", meta["Revision"]),
    ("Status", meta["Status"]), ("Date", meta["Date"]), ("Author", "Claude (AI-assisted draft)"),
    ("Approver", "Jherrod Thomas (pending)"), ("Standard", meta["Standard"]), ("Baseline", meta["Baseline"]),
    ("Source", "assurance/08-analyses/fmea/item-definition.md (generated by tools/safety/export_item_xlsx.py; do not edit)"),
  ])
  sheet(wb, "01_Document_Control", ["Revision", "Date", "Author", "Change"],
        [[meta["Revision"].split(" ")[0], meta["Date"], "Claude (AI-assisted draft)", "Initial item definition: platform, VF-001, AC-001"]],
        [10, 12, 28, 80])

  levels = tables(section_text(md, "### 1.1"))[0]
  kv_sheet(wb, "02_Item_Description", [
    ("Item", "LionDriver L2 driving assistance (ACC + ALC + driver monitoring)"),
    ("Scope", first_paragraphs(section_text(md, "## A.1"))),
    ("Classification", "SAE Level 2 driver assistance; owner-installed aftermarket device acting on production vehicle actuators"),
    ("Distinguishing notes", "Related items: " + "; ".join(f"{r['Related item']} — {r['How LionDriver differs']}"
                                                         for r in tables(section_text(md, "### 1.3"))[0])
     + ". Levels: " + "; ".join(f"{r['ID']} {r['Level']}: {r['What it is']}" for r in levels)
     + ". " + first_paragraphs(section_text(md, "### 1.2")).replace("- ", "")),
    ("Variant family VF-001", first_paragraphs(section_text(md, "## B.1"))),
    ("Assured configuration AC-001", "; ".join(f"{k}: {v}" for k, v in kv_table(section_text(md, "# Part C")).items())),
  ])

  sheet(wb, "03_Functions", ["ID", "Name", "Description"],
        [[r["ID"], r["Function"], r["Vehicle-level behavior"]] for r in tables(section_text(md, "## A.2"))[0]], [8, 30, 110])

  nfr = [[f"NFR-{i:02d}", f"{r['Item']}: {r['Relevance']}", "Legal" if i <= 3 else "Standard"]
         for i, r in enumerate(tables(section_text(md, "## A.8"))[0], 1)]
  for r in tables(section_text(md, "## A.6"))[0]:
    nfr.append([r["ID"], f"{r['Limit (platform, BL-001)']} ({r['Source']})", "Performance"])
  for line in section_text(md, "## A.6").splitlines():
    if line.startswith("- "):
      nfr.append([f"NFR-{len(nfr) + 1:02d}", line[2:], "Operating conditions"])
  sheet(wb, "04_Non_Functional_Requirements", ["ID", "Requirement", "Category"], nfr, [8, 110, 22])

  boundary = tables(section_text(md, "## A.3"))[0]
  rows = []
  for r in boundary:
    if r["In the item"]:
      rows.append(["In item", r["In the item"]])
  for r in boundary:
    out = r["Outside the item (interfaces only)"]
    if out:
      rows.append(["Adjacent system" if out.startswith("Vehicle") else "Out of item", out])
  kv_sheet(wb, "05_Boundary_Diagram", rows)

  sheet(wb, "06_External_Interfaces", ["ID", "Interface", "Counterpart", "Direction", "Data", "Integrity", "Varies by vehicle"],
        [[r["ID"], r["Interface"], r["Counterpart"], r["Direction"], r["Data"], r["Integrity measures (BL-001)"], r["Varies by vehicle"]]
         for r in tables(section_text(md, "## A.4"))[0]], [8, 30, 30, 10, 40, 50, 30])

  sheet(wb, "07_Operating_Modes", ["ID", "Mode", "Entry", "Exit", "Safety relevant"],
        [[r["ID"], r["Mode"], r["Entry"], r["Exit"], r["Safety relevant"]] for r in tables(section_text(md, "## A.5"))[0]],
        [8, 26, 40, 40, 40])

  sheet(wb, "08_Allocation_HW_SW_Mech", ["Function", "Hardware", "Software", "Mechanical"],
        [[r["Function"], r["Hardware"], r["Software"], r["Mechanical / external actuator"]]
         for r in tables(section_text(md, "### Function allocation"))[0]], [10, 40, 60, 40])

  sheet(wb, "09_Initial_Assumptions", ["Assumption", "Category", "ID"],
        [[r["Assumption"], r["Category"], r["ID"]] for r in tables(section_text(md, "## A.7"))[0]], [110, 14, 8])

  refs = ["ISO 26262-3:2018 clause 5 (item definition)", "ISO 26262-2:2018 (confirmation measures)", "SAE J3016",
          "docs/CARS.md (BL-001 supported vehicles)", "docs/SAFETY.md", "docs/LIMITATIONS.md",
          "assurance/08-analyses/fmea/analyses/hara.yaml (LD-HARA-001)", "assurance/08-analyses/fmea/analyses/fsc.yaml (LD-FSC-001)",
          "assurance/08-analyses/fmea/analyses/dfa.yaml (LD-DFA-001)", "assurance/08-analyses/fmea/baseline.yaml (BL-001)"]
  refs += [r["Item"] for r in tables(section_text(md, "## A.8"))[0]]
  sheet(wb, "10_References", ["Reference"], [[r] for r in refs], [110])

  members = [[f["id"], f["name"], f["opendbc_platform"], f["status"], m, "member"] for f in variants["families"] for m in f["members"]]
  members += [[f["id"], f["name"], f["opendbc_platform"], f["status"], m, "platform sibling (not in family)"]
              for f in variants["families"] for m in f.get("platform_siblings", [])]
  sheet(wb, "11_Variant_Families", ["Family", "Name", "opendbc platform", "Status", "Vehicle", "Relation"], members, [8, 36, 22, 14, 50, 30])

  a10 = {r["#"]: r for r in tables(section_text(md, "## A.10"))[0]}
  b4 = {r["#"]: r for r in tables(section_text(md, "## B.4"))[0]}
  sheet(wb, "12_Variant_Parameters", ["#", "Parameter", "Why it matters", "VF-001 value (BL-001)", "Source"],
        [[k, a10[k]["Parameter"], a10[k]["Why it matters"], b4.get(k, {}).get("Value", ""), b4.get(k, {}).get("Source (opendbc `229dc70` unless stated)", "")]
         for k in a10], [6, 36, 40, 60, 40])

  sheet(wb, "13_Vehicle_Catalog", ["Make", "Model", "ACC", "No ACC accel below", "No ALC below", "Harness", "LionDriver status"],
        [[c["make"], c["model"], c["acc"], c["min_acc"], c["min_alc"], c["harness"], status.get(c["name"], "Not assessed")] for c in cars],
        [14, 40, 22, 12, 12, 26, 50])

  sheet(wb, "14_Open_Items", ["ID", "Item", "Affects"],
        [[r["ID"], r["Item"], r["Affects"]] for r in tables(section_text(md, "## Open items"))[0]], [10, 110, 30])
  return wb


def main(argv=None) -> int:
  ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
  ap.add_argument("output", nargs="?", type=Path)
  ap.add_argument("--root", type=Path, default=ROOT)
  args = ap.parse_args(argv)
  root = args.root.resolve()
  out = args.output or root / DEFAULT_OUT
  out.parent.mkdir(parents=True, exist_ok=True)
  build(root).save(out)
  print(f"wrote {out}")
  return 0


if __name__ == "__main__":
  sys.exit(main())
