#!/usr/bin/env python3
"""Generate docs/safety/item/vehicle-catalog.md from docs/CARS.md and docs/safety/item/variants.yaml.

Usage: tools/safety/gen_vehicle_catalog.py [--check] [--root REPO_ROOT]

--check exits 1 if the committed catalog is out of date or variants.yaml names a vehicle not in CARS.md.
Requires PyYAML.
"""
import argparse
import re
import sys
from collections import Counter
from pathlib import Path

import yaml

ROOT = Path(__file__).resolve().parents[2]
CARS = Path("docs/CARS.md")
VARIANTS = Path("docs/safety/item/variants.yaml")
CATALOG = Path("docs/safety/item/vehicle-catalog.md")
NOT_A_CAR = {"comma body"}


def _clean(cell: str) -> str:
  return re.sub(r"\[<sup>[^<]*</sup>\]\(#footnotes\)", "", cell).strip()


def parse_cars(text: str) -> list[dict]:
  lines = text.splitlines()
  start = next(i for i, line in enumerate(lines) if line.startswith("|Make|"))
  cars = []
  for line in lines[start + 2:]:
    if not line.startswith("|"):
      break
    cells = line.split("|")[1:-1]
    make, model = _clean(cells[0]), _clean(cells[1])
    parts = re.findall(r"- \d+ ([^<]+?)<br>", cells[8])
    harness = next((p for p in parts if p.endswith("connector")), "")
    cars.append({
      "name": f"{make} {model}", "make": make, "model": model, "package": _clean(cells[2]),
      "acc": _clean(cells[3]), "min_acc": cells[4].strip(), "min_alc": cells[5].strip(), "harness": harness,
    })
  return [c for c in cars if c["name"] not in NOT_A_CAR]


def classify(cars: list[dict], variants: dict) -> tuple[dict[str, str], list[str]]:
  names = {c["name"] for c in cars}
  status, missing = {}, []
  for fam in variants["families"]:
    for m in fam.get("platform_siblings", []):
      status[m] = f"Shares opendbc platform with {fam['id']} (not assessed)"
    for m in fam["members"]:
      status[m] = f"{fam['id']} member ({fam['status'].replace('_', ' ')})"
    missing += [m for m in fam["members"] + fam.get("platform_siblings", []) if m not in names]
  for ac in variants["assured_configurations"]:
    status[ac["member"]] = f"{ac['id']} assured configuration ({ac['status'].replace('_', ' ')}); {ac['family']} member"
    if ac["member"] not in names:
      missing.append(ac["member"])
  return status, missing


def render(cars: list[dict], variants: dict) -> str:
  status, _ = classify(cars, variants)
  by_make = Counter(c["make"] for c in cars)
  out = [
    "<!-- GENERATED by tools/safety/gen_vehicle_catalog.py from docs/CARS.md and docs/safety/item/variants.yaml. Do not edit. -->",
    "",
    "# Vehicle Catalog (LD-ITEM-001 annex)",
    "",
    f"**{len(cars)} vehicles** supported by BL-001 across **{len(by_make)} makes**. Assessment status is per LD-ITEM-001 §1.2:",
    "only vehicles in an assured configuration are covered by the current safety analyses.",
    "",
    "| Status | Vehicles |",
    "|---|---|",
  ]
  counts = Counter(status.get(c["name"], "Not assessed") for c in cars)
  for k, v in sorted(counts.items(), key=lambda kv: (kv[0] == "Not assessed", kv[0])):
    out.append(f"| {k} | {v} |")
  out += ["", "| Make | Model | Package | ACC | No ACC accel below | No ALC below | Harness | LionDriver status |", "|---|---|---|---|---|---|---|---|"]
  for c in cars:
    st = status.get(c["name"], "Not assessed")
    out.append(f"| {c['make']} | {c['model']} | {c['package']} | {c['acc']} | {c['min_acc']} | {c['min_alc']} | {c['harness']} | {st} |")
  return "\n".join(out) + "\n"


def main(argv=None) -> int:
  ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
  ap.add_argument("--check", action="store_true")
  ap.add_argument("--root", type=Path, default=ROOT)
  args = ap.parse_args(argv)
  root = args.root.resolve()
  cars = parse_cars((root / CARS).read_text())
  variants = yaml.safe_load((root / VARIANTS).read_text())
  _, missing = classify(cars, variants)
  if missing:
    print("variants.yaml names vehicles not in CARS.md: " + "; ".join(missing))
    return 1
  text = render(cars, variants)
  if args.check:
    current = (root / CATALOG).read_text() if (root / CATALOG).exists() else ""
    if current != text:
      print(f"{CATALOG} is out of date; run tools/safety/gen_vehicle_catalog.py")
      return 1
    print(f"{CATALOG} up to date ({len(cars)} vehicles)")
    return 0
  (root / CATALOG).write_text(text)
  print(f"wrote {CATALOG} ({len(cars)} vehicles)")
  return 0


if __name__ == "__main__":
  sys.exit(main())
